
app = "project-faust"
primary_region = "nrt"

[env]
  DISCORD_TOKEN = "YOUR_DISCORD_BOT_TOKEN"
  OLLAMA_API_KEY = "YOUR_OPENROUTER_API_KEY"
  OLLAMA_BASE_URL = "https://openrouter.ai/api/v1"
  OLLAMA_MODEL = "mistral/mistral-7b-instruct"
  SYSTEM_PROMPT = "너는 Limbus Company 세계관의 인물 ‘파우스트(Faust)’를 연기해."
